### PR TITLE
Try to sort out migrations

### PR DESCRIPTION
**Pull request by mathiasose**
This is my suggestion for a solution for the problem described in #177, (introduced by #99 and released in v1.2.0).
If you can think of a a simpler solution, I'm open to suggestions.

- I have only run the migrations on an empty DB. I don't see any reason why the migrations would case any data loss, but it would be good to check it.
- I have not set up the test environment locally. Submitting this PR should start a CI build, which will hopefully run without any errors.

## Description
v1.2.0 broke the upgrade path from v1.1.1 by renaming migration 0006.
This meant it was possible to to a clean install of the package at v1.2.0, but not to upgrade from an existing v1.1.1 install that had applied the now nonexistent migration.

This commit tries to resolve the situation so that there will be an upgrade path from v1.1.1 to v1.2.1, as well as from v1.2.0 to v1.2.1.

The first step was to restore the v1.1.1 migrations and create a new migration 0007 so that the state of the schema was equivalent to v1.2.0.

This results in two branches in the commit graph, which necessitates a merge migration

```
      +--->0006+--->0007+--->0008+-+
      |                            |
      |                            |
0005+-+                            +-->0009_merge
      |                            |
      |                            |
      +--->0006+--->0007+----------+
```

Finally, because both branches of the graph do the same operations, create a merge migration that replaces both branches andthe merge migration itself.
Then fiddle a bit with the merge migration in an editor to remove the redundant operations, ensuring that `makemigrations --check --dry-run` continues to say `No changes detected`.
We need to include 0005 in the squash because it is the root of the branches. The new migration is therefore 0005_squash.
New installs of v1.2.1 and beyond will then only apply the merge migration, avoiding the two branches completely.

## Outcomes

- ✅ Can migrate a fresh install of this commit.
```
$  django-celery-beat git:(master) ✗ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$  django-celery-beat git:(master) ✗ rm t/db.sqlite3
rm: cannot remove 't/db.sqlite3': No such file or directory
$  django-celery-beat git:(master) ✗ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_beat.0005_add_solarschedule_events_choices_squashed_0009_merge_20181012_1416... OK
  Applying sessions.0001_initial... OK
$  django-celery-beat git:(master) ✗ python manage.py makemigrations --check --dry-run
No changes detected
```
- ✅ Can migrate from the v1.1.1 state to this state.
```
$  django-celery-beat git:(master) ✗ git checkout v1.1.1
Note: checking out 'v1.1.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 60b7fc6 Bump version: 1.1.0 → 1.1.1
$  django-celery-beat git:(60b7fc6) ✗ rm t/db.sqlite3
$  django-celery-beat git:(60b7fc6) ✗ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_beat.0005_add_solarschedule_events_choices... OK
  Applying django_celery_beat.0006_auto_20180210_1226... OK
  Applying sessions.0001_initial... OK
$  django-celery-beat git:(60b7fc6) ✗ git checkout master
Previous HEAD position was 60b7fc6 Bump version: 1.1.0 → 1.1.1
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$  django-celery-beat git:(master) ✗ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, sessions
Running migrations:
  Applying django_celery_beat.0006_auto_20180322_0932... OK
  Applying django_celery_beat.0007_auto_20180521_0826... OK
  Applying django_celery_beat.0008_auto_20180914_1922... OK
  Applying django_celery_beat.0007_auto_20181012_1414... OK
  Applying django_celery_beat.0009_merge_20181012_1416... OK
$  django-celery-beat git:(master) ✗ python manage.py makemigrations --check --dry-run
No changes detected
```
- ✅ Can migrate from the v1.2.0 state to this state.
```
$  django-celery-beat git:(master) ✗ git checkout v1.2.0
Note: checking out 'v1.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f927cde Bump version: 1.1.1 → 1.2.0
$  django-celery-beat git:(f927cde) ✗ rm t/db.sqlite3
$  django-celery-beat git:(f927cde) ✗ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_beat.0005_add_solarschedule_events_choices... OK
  Applying django_celery_beat.0006_auto_20180322_0932... OK
  Applying django_celery_beat.0007_auto_20180521_0826... OK
  Applying django_celery_beat.0008_auto_20180914_1922... OK
  Applying sessions.0001_initial... OK
$  django-celery-beat git:(f927cde) ✗ git checkout master
Previous HEAD position was f927cde Bump version: 1.1.1 → 1.2.0
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$  django-celery-beat git:(master) ✗ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, sessions
Running migrations:
  Applying django_celery_beat.0006_auto_20180210_1226... OK
  Applying django_celery_beat.0007_auto_20181012_1414... OK
  Applying django_celery_beat.0009_merge_20181012_1416... OK
$  django-celery-beat git:(master) ✗ python manage.py makemigrations --check --dry-run
No changes detected
```

### CODE REVIEW

**Comment by auvipy** [comment]
thanks for sorting this out! could you try another workaround? in another branch of your local dev env, remove all the old migrations and regenerate a new one and check what happens?

**Comment by mathiasose** [comment]
Not sure where you're going with that idea. It is essentially the same as if we'd created a squash migration for all the existing migration, except it isn't possible to upgrade from any previous version that have already applied the old migrations.

```
$  django-celery-beat git:(master) ✗ git checkout -b test
Switched to a new branch 'test'
$  django-celery-beat git:(test) ✗ rm t/db.sqlite3 
$  django-celery-beat git:(test) ✗ rm django_celery_beat/migrations/*
zsh: sure you want to delete all 13 files in /home/ose/Projects/django-celery-beat/django_celery_beat/migrations [yn]? y
$  django-celery-beat git:(test) ✗ python manage.py makemigrations django_celery_beat
Migrations for 'django_celery_beat':
  django_celery_beat/migrations/0001_initial.py
    - Create model CrontabSchedule
    - Create model IntervalSchedule
    - Create model PeriodicTask
    - Create model PeriodicTasks
    - Create model SolarSchedule
    - Alter unique_together for solarschedule (1 constraint(s))
    - Add field solar to periodictask
$  django-celery-beat git:(test) ✗ cat django_celery_beat/migrations/0001_initial.py 
# Generated by Django 2.1.2 on 2018-10-12 15:34

from django.db import migrations, models
import django.db.models.deletion
import django_celery_beat.validators
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(default='*', max_length=240, validators=[django_celery_beat.validators.minute_validator], verbose_name='minute')),
                ('hour', models.CharField(default='*', max_length=96, validators=[django_celery_beat.validators.hour_validator], verbose_name='hour')),
                ('day_of_week', models.CharField(default='*', max_length=64, validators=[django_celery_beat.validators.day_of_week_validator], verbose_name='day of week')),
                ('day_of_month', models.CharField(default='*', max_length=124, validators=[django_celery_beat.validators.day_of_month_validator], verbose_name='day of month')),
                ('month_of_year', models.CharField(default='*', max_length=64, validators=[django_celery_beat.validators.month_of_year_validator], verbose_name='month of year')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
            ],
            options={
                'verbose_name': 'crontab',
                'verbose_name_plural': 'crontabs',
                'ordering': ['month_of_year', 'day_of_month', 'day_of_week', 'hour', 'minute', 'timezone'],
            },
        ),
        migrations.CreateModel(
            name='IntervalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every', models.IntegerField(verbose_name='every')),
                ('period', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('microseconds', 'Microseconds')], max_length=24, verbose_name='period')),
            ],
            options={
                'verbose_name': 'interval',
                'verbose_name_plural': 'intervals',
                'ordering': ['period', 'every'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Useful description', max_length=200, unique=True, verbose_name='name')),
                ('task', models.CharField(max_length=200, verbose_name='task name')),
                ('args', models.TextField(blank=True, default='[]', help_text='JSON encoded positional arguments', verbose_name='Arguments')),
                ('kwargs', models.TextField(blank=True, default='{}', help_text='JSON encoded keyword arguments', verbose_name='Keyword arguments')),
                ('queue', models.CharField(blank=True, default=None, help_text='Queue defined in CELERY_TASK_QUEUES', max_length=200, null=True, verbose_name='queue')),
                ('exchange', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='exchange')),
                ('routing_key', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='routing key')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='expires')),
                ('one_off', models.BooleanField(default=False, verbose_name='one-off task')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start_time')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('total_run_count', models.PositiveIntegerField(default=0, editable=False)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('crontab', models.ForeignKey(blank=True, help_text='Use one of interval/crontab', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule', verbose_name='crontab')),
                ('interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.IntervalSchedule', verbose_name='interval')),
            ],
            options={
                'verbose_name': 'periodic task',
                'verbose_name_plural': 'periodic tasks',
            },
        ),
        migrations.CreateModel(
            name='PeriodicTasks',
            fields=[
                ('ident', models.SmallIntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('dawn_astronomical', 'dawn_astronomical'), ('dawn_civil', 'dawn_civil'), ('dawn_nautical', 'dawn_nautical'), ('dusk_astronomical', 'dusk_astronomical'), ('dusk_civil', 'dusk_civil'), ('dusk_nautical', 'dusk_nautical'), ('solar_noon', 'solar_noon'), ('sunrise', 'sunrise'), ('sunset', 'sunset')], max_length=24, verbose_name='event')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'solar event',
                'verbose_name_plural': 'solar events',
                'ordering': ('event', 'latitude', 'longitude'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='solarschedule',
            unique_together={('event', 'latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='periodictask',
            name='solar',
            field=models.ForeignKey(blank=True, help_text='Use a solar schedule', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.SolarSchedule', verbose_name='solar'),
        ),
    ]
```

**Comment by rthille** [comment]
Any chance we can get a 1.2.1 release with this fix?  I broke our dev cluster pulling in 1.2.0 :-(

**Comment by auvipy** [comment]
will try my best to release one within a week

**Comment by rthille** [comment]
Not a huge hurry, I just backed out the changes to upgrade.

**Pull request merged**
