### PR TITLE
Warn user if task selected to run was not found

### PR DESCRIPTION
**Pull request by iAnanich**

### CODE REVIEW

**Comment by iAnanich** [comment]
If user (admin) is trying to run periodic task that, for example, does not exist anymore, server will return 500, because it tries to get (and call) `delay` method of `None` object, so AttributeError gets raised. 
I added some checks so instead of server error user will get friendly message.

**Comment by iAnanich** [comment]
about tests: one simple exception test would be enough, isn't it?

**Comment by auvipy** [comment]
please proceed with that and try to make everything green!

**Comment by auvipy** [comment]
also mention the issue number you are trying to fix

**Comment by liquidpele** [comment]
@iAnanich hey there, will you be able to fix up your PR?  First you should merge latest master branch into your own branch as we have fixed some test issues, so that will tell us if your branch is actually passing the tests or not.  Plus, you'll have to fix the conflicts when you do so.  Thanks!  :)

**Comment by iAnanich** [comment]
@liquidpele merged and fixed conflicts. Now it must work well. Even tests are passing )
But haven't tried it (after update) in action yet.

**Comment by liquidpele** [comment]
@iAnanich looks like you have flake8 errors.

**Comment by iAnanich** [comment]
@liquidpele yep, just fixed it

**Pull request merged**
