### PR TITLE
Fix endless migration creation and add new migration file

### PR DESCRIPTION
**Pull request by wardal**
Fix for https://github.com/celery/django-celery-beat/issues/91 and https://github.com/celery/django-celery-beat/issues/90

### CODE REVIEW

**Comment by adriancarayol** [comment]
Same issue here

**Comment by wardal** [comment]
Which issue?

**Comment by adriancarayol** [comment]
the master branch does not have this pull yet?

**Comment by wardal** [comment]
No, it's does not merged yet.

**Comment by brianmay** [comment]
I suspect the failing tests aren't related to this pull request...

**Comment by brianmay** [comment]
Without this change, migrations might stop. Or they might not stop. It is random, it depends on the order python iterates a set. This order is not defined, we should not be relying on it.

**Comment by ACPK** [comment]
This error is causing issues for us.

**Comment by brianmay** [comment]
Note #84 appears to be a fix for the same problem.

**Comment by wardal** [comment]
@brianmay I think you are right, pull number 84 really very similar to my request. But in 84 as I can see, author does not used flakeplus to check his pull request. Also I prefer readable migration file name to understand what inside.

PS: https://pypi.python.org/pypi/flakeplus/

**Comment by jonashaag** [comment]
What can I do to help move this forward?

**Comment by jribbens** [comment]
Nothing unless someone with write access to the repository is willing to accept one of the pull requests and upload a new release.

**Comment by thedrow** [comment]
Sorry I missed this :)

**Comment by thedrow** [comment]
Thank you!

**Comment by raratiru** [comment]
Is this fixed for sure? `pip freeze` shows version `django-celery-beat==1.1.0` and I am counting 92 migrations.

**Comment by brianmay** [comment]
Fix has been merged into master, however I don't believe it is in a released version yet.

(as an aside I always review the changes makemigrations suggests and make sure they are appropriate before committing them to the project....)

**Comment by raratiru** [comment]
@brianmay  Thank you for the answer, indeed the version is 2 month old, while the pull request was merged last month.

Cool! :-)

**Comment by Ivo-Donchev** [comment]
@wardal thanks for the fix. This seems to be a very good reason for a bugfix release :) 
Are there any planned releases soon?
(Just trying to avoid dependencies to commits in my requirements.txt :D )

**Comment by thedrow** [comment]
Please track #120 for release progress.

**Comment by babus** [comment]
No updates? Probably I'll pip install from master till this fix is released. :-|

**Pull request merged**
