### PR TITLE
Test Django 5.0

### PR DESCRIPTION
**Pull request by mvaled**

### CODE REVIEW

**Comment by cclauss** [comment]
Dup #699?

**Comment by cclauss** [comment]
Either upgrade PyPy to 3.10 or drop Django 5 for PyPy.

**Comment by mvaled** [comment]
Hi @cclauss 

It does look like #699 is more complete.  So, I'm closing this one in favor of that one.

**Comment by cclauss** [comment]
# Please reopen.
You have access to run the GitHub Actions and I do not.  #699 is hung up but I will gladly close it if this one gets merged.

**Pull request closed without merging**
