### PR TITLE
Fix interval & solar validation

### PR DESCRIPTION
**Pull request by konst2**

### CODE REVIEW

**Comment by thedrow** [comment]
Can you please edit the PR's description and explain what are you trying to fix?
In addition, please include unit tests in your change.

**Comment by rsichny** [comment]
#168 
creating task with shedule other than crontab always fail the validation

**Comment by thedrow** [comment]
Have you tried the new version?

**Comment by konst2** [comment]
Yes. Updated 2 days ago. Works niсe. Thanks for your hard work!

**Comment by rsichny** [comment]
@thedrow why this was reverted? it is an issue which is reported at least 3 times (this pr, #168 and #172/#173)

**Comment by thedrow** [comment]
@konst2 tried the new release and reported back that the issue is now resolved.
Maybe I was wrong.

**Comment by thedrow** [comment]
Maybe I misunderstood. I can revert back. Please comment if I should do so.

**Comment by rsichny** [comment]
@thedrow it's not resolved. and you just got one more PR for the same thing: #179 :)

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat/pull/179 check the PR

**Pull request merged**
