### PR TITLE
remove ephem requirement

### PR DESCRIPTION
**Pull request by ransford**
No other files in this repository mention ephem, so it looks like this rather heavyweight library is a stale dependency that is no longer needed.  Also, since pip seems to want to build a shared library from source when installing ephem on Linux and Darwin, including ephem as a dependency to django_celery_beat has the (presumably) unintended consequence of requiring Python development headers.

### CODE REVIEW

**Comment by dvdmgl** [comment]
Also there is an issue [building ephen under pypy3](https://github.com/brandon-rhodes/pyephem/issues/126)

**Comment by mpiskore** [comment]
It would be awesome to merge this PR since this produces install errors both on my local setup and our Jenkins machine and this branch is 9 commits behind master. I can create my own fork and use that but I believe that everyone could benefit from keeping it simple.

**Comment by ransford** [comment]
Now it's zero commits behind master!

**Comment by DDevine** [comment]
Ephem is needed for Solar Scheduling, by the way. It is used.

**Comment by ransford** [comment]
I didn’t want to remove a real dependency so I grepped for “ephem” in the
entire source tree: no matches. Did I miss something?

**Comment by DDevine** [comment]
I thought so at first, but you didn't.
However, it needs to be documented somewhere that for Solar schedules to work then ephem (and cpython) is needed.

**Comment by thedrow** [comment]
Is ephem a dependency for Celery or django-celery-beat?

**Comment by DDevine** [comment]
It's a Celery dependency, installed an extra (ie. pip install celery[solar] IIRC).

However, I don't know if things will crash if somebody creates a Solar based task in Django Admin when ephem is not installed.

**Pull request merged**
