### PR TITLE
fix "ModuleNotFoundError: No module named 'celery.utils.encoding'"

### PR DESCRIPTION
**Pull request by torchingloom**

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
can you also check the test failures?

**Comment by thedrow** [comment]
> can you also check the test failures?

The test failures are unrelated.
We need to invest some work here since we've done some changes in Celery 5 which break the test suite like introducing `pytest-celery`.

**Review by thedrow — APPROVED** [review]
LGTM

**Review by auvipy — APPROVED** [review]

**Comment by mfonville** [comment]
Please also publish it as an updated release, so that we can all install this fix directly with `pip` :-)

**Comment by auvipy** [comment]
let me check all the related open issues before a pypi release

**Pull request merged**
