### PR TITLE
Added PeriodicTasks verbose name and it's zh_Hans translate

### PR DESCRIPTION
**Pull request by zengqiu**
I added `PeriodicTasks` to `Admin Site`, but it can't translate, so I added the verbose name in `PeriodicTasks`'s `Meta` and update zh_Hans translate.

### CODE REVIEW

**Comment by zengqiu** [comment]
@auvipy Is there any problems with this pull request? Why isn't it being merged?

**Comment by auvipy** [comment]
Yes all the builds are failing

**Comment by zengqiu** [comment]
@auvipy I added a migration file, all checks have passed.

**Review by thedrow — APPROVED** [review]

**Comment by thedrow** [comment]
Thank you for your contribution!

**Pull request merged**
