### PR TITLE
Increase dep django-timezone-field range

### PR DESCRIPTION
**Pull request by richardARPANET**
Fixes error ImportError: cannot import name 'six'  in django  django==3.0.3. installing 4.0 in this django version fixes that error

```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/amnesia/.pyenv/versions/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django_celery_beat/models.py", line 6, in <module>
    import timezone_field
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/timezone_field/__init__.py", line 1, in <module>
    from timezone_field.fields import TimeZoneField
  File "/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/timezone_field/fields.py", line 5, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/amnesia/.pyenv/versions/sheet2api/lib/python3.8/site-packages/django/utils/__init__.py)
````

### CODE REVIEW

**Comment by D3X** [comment]
@richardARPANET the new version of `django-timezone-field` is not compatible with `django < 2.2` which is still supported by `django-celery-beat` (as of version 1.6).

There's a PR that handles this issue properly: #300

**Comment by D3X** [comment]
@auvipy, @richardARPANET, I think this can be closed now

**Comment by yashas123** [comment]
Any update for this? Still not able to use this with django 3 since it can't support django-timezone-field-4.0, and 3.1 doesn't work with django 3, please update.

**Comment by auvipy** [comment]
install from github master

**Pull request closed without merging**
