### PR TITLE
Fix CI: Change assert self.app.timezone.zone  to assert self.app.timezone.key

### PR DESCRIPTION
**Pull request by stasfilin**
Good afternoon,
This Pull Request is a quick fix for CI.

`The error message AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'zone'`

So, we can use 
`self.app.timezone.key`

### CODE REVIEW

**Comment by auvipy** [comment]
thanks for the PR. will merge after CI is green

**Comment by stasfilin** [comment]
@auvipy Good morning 

I see that the lint is failed

```
Failed to reach any of the inventories with the following issues:

  intersphinx inventory 'https://celery.readthedocs.io/en/master/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for URL: https://docs.celeryq.dev/en/mastethe lint is failed 



This one is strange. Do you know the new URL that we need to use?

Thanks

**Comment by auvipy** [comment]
Instead of https://celery.readthedocs.io/en/master/ this should be https://celery.readthedocs.io/en/main/

**Comment by stasfilin** [comment]
@auvipy Hi again, I did changes

image
image

**Review by auvipy — APPROVED** [review]
all green. thanks

**Pull request merged**
