### PR TITLE
Fix locale

### PR DESCRIPTION
**Pull request by lsaavedr**
Hello,

with these changes I can see the 'es' translations in the django admin, I do not tested what happens in the sphinx documentation

regards,
Luis

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
how you have any Spanish colleagues to check this?

**Comment by lsaavedr** [comment]
> how you have any Spanish colleagues to check this?

I'm from Chile :P

Thanks!

**Comment by auvipy** [comment]
> > how you have any Spanish colleagues to check this?
> 
> I'm from Chile :P
> 
> Thanks!

sorry never mind :D

**Comment by auvipy** [comment]
need to make sure this ain't gonna break anything

**Comment by lsaavedr** [comment]
because I'm from Chile? lol jejejej na, please check that sphinx it's okay... thanks!

**Comment by lsaavedr** [comment]
thanks!

**Pull request merged**
