### PR TITLE
Support for german translation

### PR DESCRIPTION
**Pull request by contmp**
- Added the german po-file
- Wrapped gettext_lazy around PeriodicTaskAdmin fieldset labels to extend i18n support

### CODE REVIEW

**Comment by auvipy** [comment]
can you mention native german speakers to verify the changes?

**Comment by contmp** [comment]
Maybe @arneb, he is an experienced django/github developer. @arneb would you be so kind to review and approve this translation?

**Comment by arneb** [comment]
@contmp @auvipy I have reviewed the changed and did not found any problems. I am a german native speaker.

**Comment by contmp** [comment]
Thank you for the quick review @arneb

**Review by auvipy — APPROVED** [review]

**Pull request merged**
