### PR TITLE
Add missing validation to PeriodicTask.save (fixes #88)

### LINKED ISSUE #88: AttributeError: 'NoneType' object has no attribute 'is_due'
Hi, we're running Django==1.11.3 &celery==4.1.0 & django-celery-beat==1.0.1  on only one server.
we've being experiencing this error ：
`AttributeError: 'NoneType' object has no attribute 'is_due'`
The Traceback is:
```
2017-10-17 09:44:31,975: ERROR/Beat] Process Beat
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 634, in run
    self.service.start(embedded_process=True)
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 558, in start
    interval = self.scheduler.tick()
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 265, in tick
    self.populate_heap()
  File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 246, in populate_heap
    for e in values(self.schedule)]
  File "/usr/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 99, in is_due
    return self.schedule.is_due(self.last_run_at)
AttributeError: 'NoneType' object has no attribute 'is_due'
[2017-10-17 09:44:32,006: WARNING/Beat] Process Beat:
[2017-10-17 09:44:32,007: WARNING/Beat] Traceback (most recent call last):
[2017-10-17 09:44:32,007: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/billiard/process.py", line 327, in _bootstrap
[2017-10-17 09:44:32,007: WARNING/Beat] self.run()
[2017-10-17 09:44:32,007: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 634, in run
[2017-10-17 09:44:32,007: WARNING/Beat] self.service.start(embedded_process=True)
[2017-10-17 09:44:32,007: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 558, in start
[2017-10-17 09:44:32,007: WARNING/Beat] interval = self.scheduler.tick()
[2017-10-17 09:44:32,008: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 265, in tick
[2017-10-17 09:44:32,008: WARNING/Beat] self.populate_heap()
[2017-10-17 09:44:32,008: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/celery/beat.py", line 246, in populate_heap
[2017-10-17 09:44:32,008: WARNING/Beat] for e in values(self.schedule)]
[2017-10-17 09:44:32,008: WARNING/Beat] File "/usr/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 99, in is_due
[2017-10-17 09:44:32,008: WARNING/Beat] return self.schedule.is_due(self.last_run_at)
[2017-10-17 09:44:32,008: WARNING/Beat] AttributeError: 'NoneType' object has no attribute 'is_due'
```

Could you please check out and tell us what could be causing this ?

### PR DESCRIPTION
**Pull request by hartwork**
Meant to fix #88

### CODE REVIEW

**Comment by liquidpele** [comment]
This looks good... BUT... it really needs tests for the negative side.  i.e. a test that verifies that it raises the correct exceptions when you try to do save a periodic task with multiple schedule types set.

**Comment by hartwork** [comment]
> it really needs [..] a test that verifies that it raises the correct exceptions when you try to do save a periodic task with multiple schedule types set.

Have you seen this existing one?:

https://github.com/celery/django-celery-beat/blob/db68a4997420e141b002b555d0d58e98f32a6a4f/t/unit/test_admin.py#L66-L75

**Comment by liquidpele** [comment]
Right, but now it should also test that the .save() method raises the same error, which is the change this PR makes.

**Comment by hartwork** [comment]
> Right, but now it should also test that the .save() method raises the same error, which is the change this PR makes.

As you like, can do. Done, please check the latest commit above.

**Comment by liquidpele** [comment]
Awesome, thanks!

**Pull request merged**
