### PR TITLE
Remove requirements/test-djangoXY.txt

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #727

Concentrate testing state in just two files instead of lots of one-line files.

### CODE REVIEW

**Comment by Nusnus** [comment]
CleanShot 2024-02-08 at 19 08 38

LGTM - do you want also to maybe rename the job on the way? @cclauss

**Review by Nusnus — APPROVED** [review]

**Comment by cclauss** [comment]
`build` is often used as a default job name in the GitHub Actions docs so I am OK with it.

If however, you want to suggest a different name, I have no objections.

**Comment by cclauss** [comment]
Thanks much as always!!  I could use your help with getting a release published to PyPI (see `Makefile`).
Please see issue 680 for the history but I feel like this codebase is ready for a PyPI release that supports Dj5.0.
* https://github.com/celery/django-celery-beat/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed

**Comment by Nusnus** [comment]
> Thanks much as always!!  I could use your help with getting a release published to PyPI (see `Makefile`).
> Please see issue 680 for the history but I feel like this codebase is ready for a PyPI release that supports Dj5.0.
> * https://github.com/celery/django-celery-beat/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed

Let me see what I can do 🙏

**Pull request merged**
