### PR TITLE
Update PeriodicTaskAdmin list display

### PR DESCRIPTION
**Pull request by khanh96le**
PR for issue #620

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
can you describe what does the change do?

**Comment by khanh96le** [comment]
> can you describe what does the change do?

**Comment by khanh96le** [comment]
@auvipy 
I described the proposed changes in this issue: https://github.com/celery/django-celery-beat/issues/620

To make it more clear, you can see the image below. I think the schedule (which is currently mixed with the task name) should have its own column.

From
Screen Shot 2023-02-06 at 15 34 25

To
Screen Shot 2023-02-06 at 15 39 00

**Comment by auvipy** [comment]
can you check this PR as well https://github.com/celery/django-celery-beat/pull/622?

**Comment by khanh96le** [comment]
Seem like the #622 PR already covers the changes in my PR.
Therefore, I will close this one, and review #622 instead.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
