### PR TITLE
replace django 3.1 to django 4.0

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by saschahofmann** [comment]
Anything needed to get this over the line?

**Comment by auvipy** [comment]
little work remain

**Comment by saschahofmann** [comment]
If you point me to where I might be able to take a look!

**Comment by auvipy** [comment]
> If you point me to where I might be able to take a look!

https://github.com/celery/django-celery-beat/pull/450 this one is pre requisite. you can help with that

**Comment by auvipy** [comment]
related https://github.com/celery/django-celery-results/pull/272

**Pull request merged**
