### PR TITLE
Django>=3.2,<4.2

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by Kraust** [comment]
Any update on this?

**Comment by snmishra** [comment]
The following patch works for me if it helps speed this up.

From e9a077acad0adc8aa800b8cf17ac5677e145f544 Mon Sep 17 00:00:00 2001
From: Satya Mishra <satya.devel@gmail.com>
Date: Wed, 31 Aug 2022 10:05:54 -0500
Subject: [PATCH] Allow Django 4.1

---
 requirements/docs.txt          | 2 +-
 requirements/runtime.txt       | 2 +-
 requirements/test-django.txt   | 2 +-
 requirements/test-django41.txt | 1 +
 tox.ini                        | 8 +++++---
 5 files changed, 9 insertions(+), 6 deletions(-)
 create mode 100644 requirements/test-django41.txt

diff --git a/requirements/docs.txt b/requirements/docs.txt
index cb78202..e37f0f9 100644
--- a/requirements/docs.txt
+++ b/requirements/docs.txt
@@ -1,4 +1,4 @@
-Django>=2.2,<4.1
+Django>=2.2,<4.2
 https://github.com/celery/sphinx_celery/archive/master.zip
 https://github.com/celery/kombu/zipball/master#egg=kombu
 https://github.com/celery/celery/zipball/master#egg=celery
diff --git a/requirements/runtime.txt b/requirements/runtime.txt
index 9e8cdd1..7613f70 100644
--- a/requirements/runtime.txt
+++ b/requirements/runtime.txt
@@ -1 +1 @@
-Django>=2.2,<4.1
+Django>=2.2,<4.2
diff --git a/requirements/test-django.txt b/requirements/test-django.txt
index cfd59b1..f7979f8 100644
--- a/requirements/test-django.txt
+++ b/requirements/test-django.txt
@@ -1 +1 @@
-Django>=3.2,<4.1
+Django>=3.2,<4.2
diff --git a/requirements/test-django41.txt b/requirements/test-django41.txt
new file mode 100644
index 0000000..4041b77
--- /dev/null
+++ b/requirements/test-django41.txt
@@ -0,0 +1 @@
+django>=4.1,<4.2
diff --git a/tox.ini b/tox.ini
index f5393c4..e638a27 100644
--- a/tox.ini
+++ b/tox.ini
@@ -10,13 +10,14 @@ python =
 DJANGO =
     3.2: django32
     4.0: django40
+    4.1: django41
 
 [tox]
 envlist =
     py37-django{32}
-    py38-django{32,40}
-    py39-django{32,40}
-    py310-django{32,40}
+    py38-django{32,40,41}
+    py39-django{32,40,41}
+    py310-django{32,40,41}
     pypy3-django{32}
     flake8
     apicheck
@@ -34,6 +35,7 @@ deps=
 
     django32: -r{toxinidir}/requirements/test-django32.txt
     django40: -r{toxinidir}/requirements/test-django40.txt
+    django41: -r{toxinidir}/requirements/test-django41.txt
 
     linkcheck,apicheck: -r{toxinidir}/requirements/docs.txt
     flake8,pydocstyle: -r{toxinidir}/requirements/pkgutils.txt
-- 
2.34.1

**Comment by Acetonen** [comment]
update this pleeeeeeeease (

**Comment by hoefling** [comment]
At least when it comes to the CI, the failures are not related to Django bump and should be amended with the next release of `sphinx-celery` that includes https://github.com/celery/sphinx_celery/pull/40.

**Comment by nasir733** [comment]
any updates?

**Comment by centromere** [comment]
Is this ready to go?

**Comment by ja-gooding** [comment]
What is the root issue here? Why have there been issues with the past two minor version bumps of Django? It shouldn't be taking weeks to just get `pip install` working because version requirements are overly restricted.

**Comment by qcoumes** [comment]
We're also kinda stuck on Django 4.0 waiting for this PR. This also happened when Django 4.0 was released as far as I remember

**Comment by goatwu1993** [comment]
[sphinx_celery](https://github.com/celery/sphinx_celery) already fixed at https://github.com/celery/sphinx_celery/pull/40.

sphinx_celery warning should disappear after rerun.

**Comment by goatwu1993** [comment]
@auvipy can you take a look?

LGTM analysis failed for some unknown reason. Is it because I merge into dj42 branch instead of main :(

**Comment by BartKalkman** [comment]
How can it take more then 2 months to update the requirements. Please fix this!

**Comment by virogenesis** [comment]
Lets gooo 🎉

**Pull request merged**
