### PR TITLE
Fix crashes and ensure usage of correct timezone for solar and crontab schedules

### PR DESCRIPTION
**Pull request by DDevine**
In relation to https://github.com/celery/django-celery-beat/issues/55

### CODE REVIEW

**Comment by DDevine** [comment]
I have continued the work on making solar schedules work. This is related to https://github.com/celery/django-celery-beat/issues/57

**Comment by RabidCicada** [comment]
Could we get a little attention to this?...It solves two major problems :)

**Comment by DDevine** [comment]
The failed check appears to be a problem with the test/testing environment and not my code, just by the way.

**Comment by RabidCicada** [comment]
@DDevine It looks like it doesn't like the spaces after lines 63,64.65 in `/home/travis/build/celery/django-celery-beat/django_celery_beat/models.py`.  Could you remove them and see if it makes flake8 happy?

**Comment by DDevine** [comment]
Note that t/unit/test_schedulers.py::test_models::test_SolarSchedule_schedule failing is intentional - until https://github.com/celery/celery/pull/4103 is merged this test will fail as it is due to a bug in Celery.

Sorry about all the silly errors, especially the linter errors. I'll be more careful in the future.

**Comment by auvipy** [comment]
no worries. thanks for your valuable contributions

**Pull request merged**
