### PR TITLE
Adding inline to each schedule admin to show PeriodicTasks using the schedule

### PR DESCRIPTION
**Pull request by truthdoug**
See issue #742

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
would you mind sharing the screenshots of the UI of changes, please?

**Comment by truthdoug** [comment]
Before: issue-742-befoe

After: 
issue742-after

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
should be a good addition...

**Comment by auvipy** [comment]
accepting as with the hope of not introducing any regression.

**Pull request merged**
