### PR TITLE
Migration tests, fix migration bug, and clean up test matrix.  

### PR DESCRIPTION
**Pull request by liquidpele**
In this PR:

1. Set up tests to upgrade from 1.1.1, 1.20, 1.3.0, 1.4.0.   After upgrade, run migrations back to 0001 and then forward again to ensure no issues.  
2. Add a migration to remove bad migration history caused by the migration squash a while back.  This was only causing an error when ugprading from 1.3.0 and then going backward again, caught by the new tests mentioned above. 
3. Update all test VMs to xenial (ubuntu 6.04).  Add erlang fixing code to a central location for all builds. 
4. Ensure we get latest sqlite due to a very strange timing bug with sqlite and migrations that would cause migrations to randomly fail. 
5. Add python 3.6, and django 2.1 to text matrix.

### CODE REVIEW

**Comment by justmobilize** [comment]
@liquidpele are you going to do this for all versions?

**Comment by liquidpele** [comment]
Yes, just playing with getting one working first... tox and travis-ci are finicky AF.

**Comment by justmobilize** [comment]
I recommend looking here: #210 and not squashing the migration. You will have users in different spots and this will never work for all

**Comment by auvipy** [comment]
Seems you are going to be martyred for fixing this :dagger:

**Comment by liquidpele** [comment]
Ha.  Such an annoying issue.  I can't reproduce it anywhere except the damn travis-ci environment!

**Comment by liquidpele** [comment]
@auvipy @justmobilize 

I think this is finally done!  Apparently the issue I was debugging was a but with django migrations and older sqlite.... basically it would just randomly fail saying that a field didn't exist, but re-running the same test again would make it pass, and I couldn't reproduce it locally.  Updating all tests to run on xenial seems to have stopped the failures.

**Pull request merged**
